---
- name: Install software on the local machine
  hosts: localhost
  gather_facts: true
  become: yes

  tasks:
    - name: Update package manager cache
      apt:
        update_cache: yes
      when: ansible_pkg_mgr == 'apt'

    - name: Install prerequisite packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present
      when: ansible_pkg_mgr == 'apt'

    - name: Add Jenkins GPG key
      apt_key:
        url: https://pkg.jenkins.io/debian/jenkins.io.key
        state: present
      when: ansible_pkg_mgr == 'apt'

    - name: Add Jenkins repository
      apt_repository:
        repo: deb https://pkg.jenkins.io/debian-stable binary/
      when: ansible_pkg_mgr == 'apt'

    - name: Install Jenkins
      apt:
        name: jenkins
        state: present
      when: ansible_pkg_mgr == 'apt'

    - name: Start Jenkins service
      service:
        name: jenkins
        state: started
        enabled: yes
      when: ansible_pkg_mgr == 'apt'

    - name: Install Maven
      apt:
        name: maven
        state: present
      when: ansible_pkg_mgr == 'apt'

    - name: Install Docker
      apt:
        name:
          - docker.io
          - docker-compose
        state: present
      when: ansible_pkg_mgr == 'apt'

    - name: Add current user to Docker group
      user:
        name: "{{ ansible_env.USER }}"
        groups: docker
        append: yes

    - name: Install kubectl
      shell: curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" && chmod +x kubectl && sudo mv kubectl /usr/local/bin/
      args:
        creates: /usr/local/bin/kubectl

    - name: Install Git
      apt:
        name: git
        state: present
      when: ansible_pkg_mgr == 'apt'

    - name: Install eksctl
      shell: curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp && sudo mv /tmp/eksctl /usr/local/bin
      args:
        creates: /usr/local/bin/eksctl

    - name: Upgrade AWS CLI to version 2
      shell: curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && unzip awscliv2.zip && sudo ./aws/install
      args:
        chdir: /tmp
        creates: /usr/local/bin/aws
